####  RBAC是Kubernetes中一种权限控制机制，允许管理员根据角色和角色绑定来定义用户或服务账号的访问权限。通过RBAC，可以细粒度地管理谁可以对集群资源进行何种操作。
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homo-prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---

#### 2、配置k8s服务账号及集群角色绑定
apiVersion: v1
kind: ServiceAccount  #创建一个服务账号
metadata:
  name: homo-prometheus
  namespace: homo-prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding            #集群角色绑定
metadata:
  name: homo-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homo-prometheus
subjects:
  - kind: ServiceAccount           #与服务账号进行绑定
    name: homo-prometheus
    namespace: homo-prometheus