kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka
  namespace: homo-test
spec:
  serviceName: kafka-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: default.registry.tke-syyx.com/syyx-tpf/bitnami-kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: kafka-listener
              containerPort: 9092
              protocol: TCP
            - name: kafka-listener2
              containerPort: 9093
              protocol: TCP
            - name: kafka-jmx
              containerPort: 5555
              protocol: TCP
          volumeMounts:
            - name: kafka-volume  #这是在 volumes 部分定义的卷名称。安装目录/opt/bitnami/kafka
              mountPath: /var/lib/kafka  #这是容器内的路径，你希望把卷挂载到这个路径，注意该目录是绝对路径，否则挂载无效。（建议进去容器pwd看当前路径确认）
              subPath: kafka-data #这是卷中的子目录，表示你只想把PersistentVolume 中的kafka-data挂载到/var/lib/kafka上
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT" #外部监听可以使用SSL确保安全性
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-service:9092,EXTERNAL://kafka-service-client:9093"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: 'true'
            - name: JMX_PORT
              value: "5555"
            - name: KAFKA_JMX_OPTS
              value: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka-service-client -Dcom.sun.management.jmxremote.rmi.port=5555"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
            - name: KAFKA_HEAP_OPTS
              value: '-Xms512M -Xmx512M'
      volumes:
      - name: kafka-volume
        persistentVolumeClaim:
          claimName: homo-test-pvc



