apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-client
  namespace: homo-test
spec:
  selector:
    app: zookeeper
  ports:
    - name: for-client
      protocol: TCP
      port: 2181
      targetPort: 2181
  type: LoadBalancer # 根据需求调整为LoadBalancer或ClusterIP
