apiVersion: v1
kind: Service
metadata:
  name: nocobase-for-client
spec:
  selector:
    app: nocobase
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # 如果你希望暴露服务到外部可以用 LoadBalancer，或者使用 ClusterIP 仅限于集群内部访问
