kind: Secret
apiVersion: v1
metadata:
  name: postgresql-secret
  namespace: yh-crawler
data:
  POSTGRES_DB: cG9zdGdyZXM= #postgres
  POSTGRES_HOST: cG9zdGdyZXM= #postgres
  POSTGRES_PASSWORD: MTIzNDU2 #123456
  POSTGRES_USER: cG9zdGdyZXM= #postgres
type: Opaque