kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:
  namespace:
  labels:
    dir: EXAMPLE-DIR
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-subdir-client