apiVersion: v1
kind: Service
metadata:
    name: EXAMPLE-SERVICE
    namespace: EXAMPLE-NAMESPACE
spec:
    type: ClusterIP
    clusterIP: None
    selector:
        app: EXAMPLE-APP
    ports:
    - protocol: TCP
      port: -1
      targetPort: -1
