apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: SIMPLE
      server: SIMPLE
    name: SIMPLE
contexts:
  - context:
      cluster: SIMPLE
      user: SIMPLE
    name: SIMPLE
current-context: SIMPLE
kind: Config
preferences: {}
users:
  - name: SIMPLE
    user:
      token: SIMPLE