apiVersion: v1
kind: Service
metadata:
  name: postgrest-service
  namespace: wuhui-dev-dubian
spec:
  selector:
    app: postgrest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
